### ISSUE TITLE
Endpoints returning products should use the latest price

### ISSUE THREAD

**Issue by ArktinenKarpalo** [TKOaly/rv-backend#127]
The price table is supposed to be used to keep track of the buy and sell prices of different product batches. Products are supposed to be sold according to the latest price first until they run out, see:

- #129 

Because of this we must choose which prices we show to users and admins:

- When users are checking the price they must know what is the price of the next sold product, which is the latest price that still has stock. This means that the user facing product endpoints should include the "newest" product price.
- Admins may also need access to the prices of other batches that are still in stock. I should be investigated if there is need for these and matching batch stocks as a list.

https://github.com/TKOaly/rv-backend/blob/b49d6fb079d88b3367fb11d1ac1534390ec63bd2/src/db/productStore.js#L23-L40
There are many other endpoints to consider as well.

**Comment by Jokauppi** [comment]
The are probably many other endpoints that don't handle getting the latest price either. These should be investigated.

**Comment by Jokauppi** [comment]
It was chosen to not implement multiple simultaneous prices. There may still be problems with this flow though. Issue will be updated.

**Comment by ArktinenKarpalo** [comment]
There is a reason to believe that issues concerning "PRICE" table queries missing endTime where clause have been fixed now.
So closing this for now.
