### ISSUE TITLE
Extra arguments for function getDepositHistory

### ISSUE THREAD

**Issue by Tuupertunut** [TKOaly/rv-backend#139]
https://github.com/TKOaly/rv-backend/blob/c4794e30c2a2a0a57507351a23fce11be3124599/src/routes/admin/history.js#L7
There should not be any arguments

**Comment by ArktinenKarpalo** [comment]
Fixed in https://github.com/TKOaly/rv-backend/commit/656c26d90e8064188e5a0b70d771614dc3576f9f
