### ISSUE TITLE
Fix encoding issues in database.

### ISSUE THREAD

**Issue by Tuupertunut** [TKOaly/rv-backend#2]
There are encoding issues in the old RV database. Fix them before migrating to new RV.

**Comment by ArktinenKarpalo** [comment]
More info needed, do encoding issues imply encoding of letters Ä Ö in product names etc. or are there some other issues as well?

**Comment by ArktinenKarpalo** [comment]
See #https://github.com/TKOaly/rv-backend/pull/147/commits/9fb186c846d1bf156e5e2ee9e46ddbf021581626
