### ISSUE TITLE
Disallow empty values for PATCH /user and POST /user/changePassword

### ISSUE THREAD

**Issue by Jokauppi** [TKOaly/rv-backend#64]
The user edit and password change allow the user to submit any field as undefined potentially leading to an account without a password or username disabling access to the account.

**Comment by Tuupertunut** [comment]
PATCH is supposed to only change those fields that are defined. There is a function deleteUndefinedFields which ensures that no undefined fields get passed to the database.

**Comment by Jokauppi** [comment]
Values were passed as empty strings. This PR reverts some constraints in validation that were introduced with the OpenAPI validation.
