### ISSUE TITLE
Adding second product fails in development db

### ISSUE THREAD

**Issue by Jokauppi** [TKOaly/rv-backend#70]
## How to reproduce
- Create two new products
- Second addition fails and server crashes

## Cause
RVITEM itemid sequence value is probably not set correctly as the second product is inserted with itemid 2, causing an error as a product with this itemid already exists in the seed data.

**Comment by Tuupertunut** [comment]
Possible cause: There is a piece of code in every seeding script that tries to increment the sequence to the highest value in the seed data. The RVITEM table was renamed RVITEM_ALL in a recent commit, but the seeding script still refers to the sequence of RVITEM.itemid.
