### ISSUE TITLE
Github ohtu2018 fork is annoying

### ISSUE THREAD

**Issue by ArktinenKarpalo** [TKOaly/rv-backend#88]
Github suggests pull requests to ohtu2018 repo instead of the current repo. 
Should figure out why and how to default to current.
Maybe related: https://github.com/orgs/community/discussions/11729

**Comment by Jokauppi** [comment]
Yep seems like the only way to fix this right now is to extract the fork. Manually doing it would mean losing issues and other repo related stuff. But it might be possible to request that from customer support without losing that: https://support.github.com/request/fork?tags=hubberfy_repositories Should we request this? Would make sense as this is obviously the base repo now. It would also get rid of the "n commits ahead" message.

**Comment by ArktinenKarpalo** [comment]
I sent a ticket about it. Its odd that they don't have just a button for doing this.

**Comment by Jokauppi** [comment]
Yea would seem like a logical feature to implement in the repo settings.
